[build]
  # Build command that ensures toolchain and directories exist before Next.js build
  # Force clean install to avoid cache issues
  command = "npm ci && npm run install-toolchain && npm run build"

  # Publish directory for Next.js on Netlify
  # For Next.js with API routes, this should be omitted to let the plugin handle it
  # publish = ".next"

# Explicitly configure the Next.js plugin to ensure API routes work
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Enable Netlify Functions
[functions]
  directory = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

  # Ensure we're in production mode
  NODE_ENV = "production"

  # Next.js specific environment variables
  NEXT_PUBLIC_USE_REAL_BACKEND = "true"

  # WebSocket Configuration (disabled for serverless deployment)
  NEXT_PUBLIC_ENABLE_WEBSOCKET = "false"

  # Go version and configuration
  GO_VERSION = "1.21"
  GOROOT = "/usr/local/go"
  GOPATH = "/opt/buildhome/go"

  # Python version (for future use)
  PYTHON_VERSION = "3.11"

  # SQLite configuration
  SQLITE_DISABLE_LFS = "1"

  # Build flags for native dependencies
  npm_config_build_from_source = "true"

  # Ensure proper module resolution
  NODE_OPTIONS = "--max-old-space-size=4096"

  # Force case-sensitive module resolution
  FORCE_COLOR = "1"

  # SSE Configuration (for real-time updates)
  NEXT_PUBLIC_SSE_URL = "/.netlify/functions/stream"

  # Supabase Configuration (set these in Netlify UI for security)
  # NEXT_PUBLIC_SUPABASE_URL = "https://your-project.supabase.co"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"
  # SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"
  # API_KEY_ENCRYPTION_KEY = "your-32-char-encryption-key"

# Build processing settings
[build.processing]
  skip_processing = false

# Build ignore configuration - always build for now
# [build.ignore]
#   command = "exit 1"

# Headers for static assets
[[headers]]
  for = "/output/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA behavior (if needed)
# Note: API routes are handled by Next.js App Router, not Netlify Functions
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# Functions configuration (disabled for now)
# [functions]
#   directory = "netlify/functions"

# Build hooks for different branches
[context.production]
  command = "npm ci && npm run install-toolchain && npm run build"

[context.deploy-preview]
  command = "npm ci && npm run install-toolchain && npm run build"

[context.branch-deploy]
  command = "npm ci && npm run install-toolchain && npm run build"
