[build]
  # Build command that ensures toolchain and directories exist before Next.js build
  command = "npm run install-toolchain && npm run build"

  # Publish directory (Next.js default)
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

  # Ensure we're in production mode
  NODE_ENV = "production"

  # Go version (for future use when real compilation is implemented)
  GO_VERSION = "1.21"

  # Python version (for future use)
  PYTHON_VERSION = "3.11"

  # SQLite configuration
  SQLITE_DISABLE_LFS = "1"

  # Build flags for native dependencies
  npm_config_build_from_source = "true"

# Build processing settings
[build.processing]
  skip_processing = false

# Include necessary files in the build
[build.ignore]
  # Don't ignore these important directories
  command = "exit 1"

# Headers for static assets
[[headers]]
  for = "/output/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA behavior (if needed)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Functions configuration (if you plan to use Netlify Functions)
[functions]
  directory = "netlify/functions"

# Build hooks for different branches
[context.production]
  command = "npm run install-toolchain && npm run build"

[context.deploy-preview]
  command = "npm run install-toolchain && npm run build"

[context.branch-deploy]
  command = "npm run install-toolchain && npm run build"
