[build]
  # Build command for Netlify - skip toolchain installation since we use GitHub Actions for compilation
  # Force clean install to avoid cache issues
  command = "npm ci && npm run build"

  # Publish directory for Next.js on Netlify
  # For Next.js with API routes, this should be omitted to let the plugin handle it
  # publish = ".next"

# Explicitly configure the Next.js plugin to ensure API routes work
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Enable Netlify Functions
[functions]
  directory = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

  # Ensure we're in production mode
  NODE_ENV = "production"

  # Next.js specific environment variables
  NEXT_PUBLIC_USE_REAL_BACKEND = "true"

  # WebSocket Configuration (disabled for serverless deployment)
  NEXT_PUBLIC_ENABLE_WEBSOCKET = "false"

  # Go compilation disabled for Netlify - using GitHub Actions instead
  # GO_VERSION = "1.21"
  # GOROOT = "/usr/local/go"
  # GOPATH = "/opt/buildhome/go"

  # Python version (for future use)
  PYTHON_VERSION = "3.11"

  # SQLite configuration
  SQLITE_DISABLE_LFS = "1"

  # Build flags for native dependencies
  npm_config_build_from_source = "true"

  # Ensure proper module resolution
  NODE_OPTIONS = "--max-old-space-size=4096"

  # Force case-sensitive module resolution
  FORCE_COLOR = "1"

  # SSE Configuration (for real-time updates)
  NEXT_PUBLIC_SSE_URL = "/api/stream"

  # Supabase Configuration (set these in Netlify UI for security)
  # NEXT_PUBLIC_SUPABASE_URL = "https://your-project.supabase.co"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"
  # SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"
  # API_KEY_ENCRYPTION_KEY = "your-32-char-encryption-key"

  # GitHub Actions Configuration (set these in Netlify UI for security)
  # GITHUB_TOKEN = "your-github-token"
  # GITHUB_OWNER = "guiperry"
  # GITHUB_REPO = "next-agentify"
  # GITHUB_WORKFLOW_ID = "compile-plugin.yml"

# Build processing settings
[build.processing]
  skip_processing = false

# Build ignore configuration - always build for now
# [build.ignore]
#   command = "exit 1"

# Headers for static assets
[[headers]]
  for = "/output/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for API routes with api- prefix
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-:splat"
  status = 200
  force = false

# Redirects for special functions without api- prefix
[[redirects]]
  from = "/api/stream"
  to = "/.netlify/functions/stream"
  status = 200

[[redirects]]
  from = "/api/deploy-stream"
  to = "/.netlify/functions/deploy-stream"
  status = 200

[[redirects]]
  from = "/api/download-plugin"
  to = "/.netlify/functions/download-plugin"
  status = 200

[[redirects]]
  from = "/api/validate-*"
  to = "/.netlify/functions/validate-:splat"
  status = 200

[[redirects]]
  from = "/api/compile-*"
  to = "/.netlify/functions/compile-:splat"
  status = 200

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200

# Functions configuration
[functions]
  directory = "netlify/functions"

# Build hooks for different branches
[context.production]
  command = "npm ci && npm run build"

[context.deploy-preview]
  command = "npm ci && npm run build"

[context.branch-deploy]
  command = "npm ci && npm run build"
