[build]
  # Build command that ensures toolchain and directories exist before Next.js build
  # Force clean install to avoid cache issues
  command = "npm ci && npm run install-toolchain && npm run build"

  # Publish directory for Next.js App Router
  publish = ".next"

# Use Netlify's Next.js plugin for proper deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

  # Ensure we're in production mode
  NODE_ENV = "production"

  # Go version (for future use when real compilation is implemented)
  GO_VERSION = "1.21"

  # Python version (for future use)
  PYTHON_VERSION = "3.11"

  # SQLite configuration
  SQLITE_DISABLE_LFS = "1"

  # Build flags for native dependencies
  npm_config_build_from_source = "true"

# Build processing settings
[build.processing]
  skip_processing = false

# Build ignore configuration - always build for now
# [build.ignore]
#   command = "exit 1"

# Headers for static assets
[[headers]]
  for = "/output/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA behavior (if needed)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Functions configuration (disabled for now)
# [functions]
#   directory = "netlify/functions"

# Build hooks for different branches
[context.production]
  command = "npm ci && npm run install-toolchain && npm run build"

[context.deploy-preview]
  command = "npm ci && npm run install-toolchain && npm run build"

[context.branch-deploy]
  command = "npm ci && npm run install-toolchain && npm run build"
